from open.open import Open;
from clear.clear import Clear;
from copyall.copyall import CopyAll;
from exit.exit import Exit;
from paste.paste import Paste;
from save.save import Save;
from saveas.saveas import SaveAs;
from highlight.highlight import Highlight;
from findall.findall import FindAll;
from replaceall.replaceall import ReplaceAll;
from autosave.autosave import AutoSave;
from helpers.toggleAutoSave import toggleAutoSave
from countwords.countwords import CountWords