from Components.open import Open;
from Components.clear import Clear;
from Components.copyall import CopyAll;
from Components.exit import Exit;
from Components.paste import Paste;
from Components.save import Save;
from Components.saveas import SaveAs;
from Components.highlight import Highlight;
from Components.findall import FindAll;
from Components.replaceall import ReplaceAll;
from Components.autosave import AutoSave;
from Components.toggleAutoSave import toggleAutoSave